flux-framework/flux-pmix

.github/workflows/main.yml, .mergify.yml, src/test/backtrace-all.sh, src/test/checks-annotate.sh, src/test/checks-lib.sh, src/test/checks_run.sh, src/test/docker/docker-run-checks.sh, src/test/docker/focal/Dockerfile
This PR adds a Dockerfile for `focal`, `docker-run-checks.sh` from flux-core, and a github workflow to enable CI on all PRs in this repo. It also adds a simple `.mergify.yml` so that mergify can be enabled.
Currently, the CI wil run against ompi v5.0.x branch in Ubuntu focal only, though the workflow is set up to easily allow different branches of OpenMPI to be built and installed.
This is built on top of the current `main`, so no checks are run. @garlick, if you want, instead of merging this PR you could just pull the commits into your existing testsuite PR so that `make check` actually does something. Otherwise, this PR could be merged and the testsuite PR rebased on top.
=> add ci support for pull requests

Makefile.am, configure.ac, src/shell/plugins/Makefile.am, src/shell/plugins/main.c, t/Makefile.am, t/src/Makefile.am, t/src/getkey.c, t/src/version.c, t/t0002-basic.t
This adds the initial shell plugin, without the callbacks that enable inter-shell coordination, and with the absolute minimum namespace setup to allow the barrier test to work on a single shell.
I figured it would be good documentation in the history to build this up little by little, adding functionality and tests at each step.
This is based on top of #2, but if CI materializes, it should go in first.
=> add skeletal pmix.so plugin

Makefile.am, configure.ac, src/common/libtap/Makefile.am, src/common/libtap/tap.c, src/common/libtap/tap.h, src/shell/plugins/Makefile.am, src/shell/plugins/infovec.c, src/shell/plugins/infovec.h, src/shell/plugins/main.c, src/shell/plugins/maps.c, src/shell/plugins/maps.h, src/shell/plugins/test/infovec.c, t/src/getkey.c, t/t0002-basic.t
Push data about the job into the pmix server so that various attributes can be accessed from the client side, mainly driven by what appears to be needed to get the business card exchange use case working on a single node, and also to populate attributes mentioned in the spec v5.0 B1.1.1 business card exchange description, and attributes that popped up while tracing hello world compiled with ompi-5.0.x launched with `prterun`.
I didn't cover all of those attributes, but enough that this is a good step forward for a PR.
I did ensure that each attribute I set on the server side had a measurable effect on the client side, and added tests reflecting that.
=> plugin: set up the basic nspace

Makefile.am, configure.ac, src/common/libccan/Makefile.am, src/common/libccan/ccan/base64/LICENSE, src/common/libccan/ccan/base64/_info, src/common/libccan/ccan/base64/base64.c, src/common/libccan/ccan/base64/base64.h, src/common/libccan/ccan/base64/test/moretap.h, src/common/libccan/ccan/base64/test/run.c, src/common/libccan/licenses/BSD-MIT, src/shell/plugins/Makefile.am, src/shell/plugins/codec.c, src/shell/plugins/codec.h, src/shell/plugins/exchange.c, src/shell/plugins/exchange.h, src/shell/plugins/fence.c, src/shell/plugins/fence.h, src/shell/plugins/interthread.c, src/shell/plugins/interthread.h, src/shell/plugins/main.c, src/shell/plugins/test/codec.c, t/t0003-bizcard.t
This implements the openpmix fence callback using a collective operation similar to the one used in our pmi-1 implementation.  In fact, since that implementation was already abstracted, this pulls it in and modifies it to be usable in an external project, and to fit the openpmix fence server-side data model.  (We could consider implementing it as a generic shell service at some point but I think not today).
This also introduces a shmem message queue and codec to synchronize the pmix fence callback in the server thread with the shell's reactor thread.  The callbacks are converted into interthread messages.  The message queue was implemented with back to back `shmem://` flux_t handles, so flux's "handle watcher" and message send/recv functions could be used.
A couple of test cases demo both …
=> implement fence callback

src/shell/plugins/fence.c, t/Makefile.am, t/src/Makefile.am, t/src/barrier.c, t/t0001-ompi-sanity.t, t/t0003-barrier.t, t/t0004-bizcard.t
Problem: the` procs[]` and `info[]` arguments to the fence upcall are currently ignored.
`procs` is apparently for specifying a subset of ranks to synchronize over, which we  don't support.  If `PMIx_Fence()` is called with this set to NULL, then we get one procs entry containing a wildcard rank.  Accept this, and fail all others.
Note: in writing tests, I noticed that specifying a subset of ranks seems to hang in openpmix and we never get our upcall.  I'm not sure why this is.  However I was able to cover this code path in the server by specifying a full set of ranks rather than the wildcard, something which is probably never done.
`info` is how options are passed to the upcall.  The primary logic that needs to be implemented is to fail the fence call if the user marks any unhandled …
=> parse fence upcall parameters

.github/workflows/main.yml, .mergify.yml, Makefile.am, codecov.yml, config/ax_code_coverage.m4, config/ax_split_version.m4, configure.ac, src/test/checks_run.sh, src/test/docker/centos8/Dockerfile, t/t0002-basic.t
This PR adds the necessary groundwork and config changes to expand CI testing as noted in the title.
I figured adding a centos8 build was a good idea since RHEL is probably the initial target for this work.
We could additionally add a fedora34 build with little effort if that is desired.
=> expand CI to include centos8, distcheck, chain-lint and coverage

src/shell/plugins/main.c, src/shell/plugins/maps.c, src/shell/plugins/maps.h, t/t0002-basic.t
As described in #7, `pmix.lpeers` is set wrong when there are multiple shells on the same node.  I have not tested multiple shells, each on a unique node (probably OK).
The fix requires two components:
- ensure the hostnames in the `pmix.nmap` (the node map) are unique by appending the shell rank, but only if duplicates are detected
- set the correct value of `pmix.lpeers` in the server nspace
Neither of these fixes it independently, we need both.
=> fix incorrect setting of pmix.lpeers

.github/workflows/main.yml
Problem: The ompi version number was typo'd as v0.5.x in the names
of all workflow jobs, which results in mergify being unable to
automatically rebase and merge since status checks it expects are
never complete.
Fix the typo in the name of all current workflow jobs.
=> github: fix typo in names of all workflow jobs

src/shell/plugins/Makefile.am, src/shell/plugins/abort.c, src/shell/plugins/abort.h, src/shell/plugins/fence.c, src/shell/plugins/main.c, src/shell/plugins/test/codec.c, t/Makefile.am, t/src/Makefile.am, t/src/abort.c, t/t0005-abort.t
This adds another pmix server callback for handling `PMIx_Abort()`.  All we do is call `shell_die()`, like the the builtin pmi plugin's abort handler.  That unfortunately gets us in trouble with the czmq atexit handler, so the output is a bit noisy.  Maybe OK for now?
```
ok 4 - 1n2p abort on rank 1 works and exit code propagates
expecting success: 
test_expect_code 42 flux mini run -N2 -n2 \
-ouserrc=$(pwd)/rc.lua \
${ABORT} --status=42 --rank=1 --message=abort-test
0.072s: flux-shell[1]: FATAL: fXmz6JB.1 called PMIx_Abort: abort-test
0.073s: job.exception type=exec severity=0 fXmz6JB.1 called PMIx_Abort: abort-test
0.072s: flux-shell[1]: stderr: flux-shell: FATAL: fXmz6JB.1 called PMIx_Abort: abort-test
0.274s: flux-shell[1]: stdout: E: 21-09-23 23:15:30 [320132]dangling 'PAIR' socket …
```
=> add abort handler

.mergify.yml, src/test/docker/fedora34/Dockerfile
Apologies, this PR fixes another typo in the CI setup. The name of centos8 builder had `ommpi` instead of `ompi`.
Also I threw in a Dockerfile for fedora34 here. We can't use this for ci yet, because many tests fail in this environment. However, perhaps when someone who knows what they are doing has time, they could try to determine what in the Fedora 34 docker environment is causing the failures:
(I'd understand if you want the addition of the fedora34 Dockerfile in a different PR, just let me know)
```
bash-5.1$ ./t0003-barrier.t -d -v
sharness: loading extensions from /usr/src/t/sharness.d/00-setup.sh
sharness: loading extensions from /usr/src/t/sharness.d/01-setup.sh
sharness: loading extensions from /usr/src/t/sharness.d/flux-sharness.sh
sharness: loading extensions from …
```
=> ci: fix typo in mergify.yml, support fedora34 docker build

config/ax_flux_core.m4, src/shell/plugins/maps.c
Problem: a new interface is available to shell plugins that
would simplify maps code.
flux-framework/flux-core#3873 added 'taskids' to the object returned
by flux_shell_rank_info().  Instead of assuming block allocation
and building a base rank for the target shell by iterating over the
lower-ranked shells, just request the idset for the shell in question.
=> use new taskids shell interface

src/shell/plugins/Makefile.am, src/shell/plugins/main.c, src/shell/plugins/notify.c, src/shell/plugins/notify.h, t/Makefile.am, t/src/Makefile.am, t/src/notify.c, t/t0006-notify.t
This adds a hook that allows openpmix to notify the shell plugin of any internal errors.  The errors are logged with `shell_warn()`.
This is based on top of #16 (abort) and will need to be rebased once that is merged.
=> add error notification callback

.github/workflows/main.yml, .mergify.yml, src/shell/plugins/codec.c, src/shell/plugins/codec.h, src/shell/plugins/exchange.c, src/shell/plugins/fence.c, t/Makefile.am, t/src/barrier.c, t/t1000-ompi-basic.t
This PR fixes a bug in the fence callback - actually in the exchange class it uses - where a conditional became unconditional due to a stray semi-colon, and as a result, all ranks did not receive the entire aggregate data blob at the conclusion of the exchange.
With that fixed, ompi hello world works on two shells!  So a new sharness test that does that is added.
There is also some improved debug output, and an improvement to the barrier use case for `PMIx_Fence()`, where data was being gratuitously exchanged by the `fence_nb` server callback when it was not requested by the user.
=> fix bug in exchange class

src/shell/plugins/Makefile.am, src/shell/plugins/dmodex.c, src/shell/plugins/dmodex.h, src/shell/plugins/main.c, t/Makefile.am, t/t0007-dmodex.t
Now that ompi is working (at least for a trivial hello world) without the direct modex upcall, it not clear that we need it.  I have a version (c50e9947d321d0bf96f05e81c05324f27e446262) that appears to work, but it is pretty complicated.  It would be better to leave it out if we don't need it as it may create more loose ends than it resolves.
Add a stub version of the upcall that always returns PMIX_ERR_NOT_IMPLEMENTED, equivalent to setting the callback to NULL.  Generate the full interthread message for tracing purposes and log a warning when  the stub is called so we know when we might be missing something important.
Some testing is added to ensure we get the warning when the upcall is made.
=> generate useful debug info on direct modex upcall

Makefile.am, configure.ac, src/shell/lua.d/Makefile.am, src/shell/lua.d/openmpi@5.lua, src/shell/plugins/Makefile.am
This just adds a small lua script to load `pmix.so` when the user specifies `-ompi=openmpi@5`.  Tested when installed to the same prefix as current flux-core master.
Easily changed if we decide to do something more structured with these mpi personality scripts.
=> add mpi personality script

src/shell/plugins/main.c, t/t0002-basic.t, t/t1000-ompi-basic.t
The main thing in this PR is a fix for #26, where `mpi_hello` issues dire warnings about unlink failing.  That looks to be because we set `pmix.nsdir` to the same value as `pmix.tmpdir`, and ompi is trying to clean up `pmix.nsdir` and in the process sweeps away some shared memory segments that some other part of ompi realy wants to clean up.   The solution is to unset `pmix.nsdir`, at least for now.
Other minor attribute tweaks are included:
- setting `pmix.appnum=0`  (ompi asks for it though it is optional)
- setting `pmix.tdir.rmclean=true` (might have fixed the above had ompi checked it)
- adding tests for `pmix.nrank`, `pmix.jobs.napps` (already set properly  - make sure they remain correct)
- verification that old plugins aren't being requested by environment, in case that pops up …
=> avoid unlink errors on mpi teardown

src/shell/plugins/fence.c, src/shell/plugins/main.c, t/t0002-basic.t, t/t0003-barrier.t, t/t0004-bizcard.t, t/t1000-ompi-basic.t
I'm not sure this is the right solution to #27 but here it is for now.
The main "fix" is just to set `OMPI_MCA_btl_tcp_if_include=lo` in the test environment so that ompi ranks that are on different shells, but the same node don't get confused trying to find a working interface to communicate with tcp.
There's also a memory leak I happened across in the fence code, and some fence trace output improvement.
Finally some test expansion for the n2p3 case that is of dubious value (but I figured didn't hurt to leave in).
=> resolve ompi fence hang

src/shell/plugins/main.c, t/t0002-basic.t
Set `pmix.jobid` to the f58-encoded flux jobid, in case it might be used at some point.
Plus a tiny bit of extra testing
=> set pmix.jobid

t/src/Makefile.am, t/src/mpi_pingpong.c, t/t1000-ompi-basic.t
I was a little concerned that maybe something basic was not working because of #36 and wanted to take a smaller step between the "hello world" tests in `t1000-ompi-basic.t` and `t1001-osu-benchmarks.t` so this PR adds a little test to the former that moves a bit of data between two ranks in 1np2 and 2np2 configs.
Ultimately this didn't provide any useful clues to #36 but it still may not be a bad thing to do.
=> testsuite: add pingpong test

src/shell/plugins/abort.c, t/t0005-abort.t
Now that we've got `flux_shell_raise()`, use that here for handling a `PMIx_Abort()`.
=> call flux_shell_raise() on PMIx_Abort()

.github/workflows/main.yml, .mergify.yml, src/shell/plugins/main.c, src/test/docker/bionic/Dockerfile, src/test/docker/centos7/Dockerfile, t/src/barrier.c, t/src/getkey.c, t/src/notify.c
This PR fixes the compilation problem described in #47, and adds a gcc 4.x build via a new centos7 builder in CI.
Edit: This PR also adds a bionic Dockerfile, but does not use it in CI due to an outstanding segfault on that platform. (Will open issue)
=> build: fix build with gcc 4.x, add centos7 to ci

.mergify.yml
Problem: Mergify has deprecated strict mode merge in favor of
using merge queues.
Update the mergify config to use a default merge queue with a rebase
and merge strategy which seems to match the strict behavior from before.
Drop the status checks from the mergify.yml, since these largely seem
to be redundant with GitHub branch protections. (Mergify will not merge
until all branch protections are met.)
=> mergify: replace deprecated strict merge strategy

Makefile.am, codecov.yml, configure.ac, src/common/libutil/Makefile.am, src/common/libutil/strlcpy.c, src/common/libutil/strlcpy.h, src/shell/plugins/Makefile.am, src/shell/plugins/codec.c, src/shell/plugins/infovec.c, src/shell/plugins/interthread.c, src/shell/plugins/main.c, t/src/Makefile.am, t/src/abort.c, t/src/barrier.c, t/src/bizcard.c, t/src/notify.c
The use of `strncpy()` is error prone, so bring in `strlcpy()`.  There is actually at least one place where dropping the static initializer for a `pmix_info_t` struct created an unsafe (though unlikely) situation.
Anyway this is better hygiene.
=> use strlcpy instead of strncpy

NEWS.md
Add release notes in preparation for a v0.2.0 release.
This release is necessary in order to package a tagged version with spack due to #44.
=> NEWS.md: add release notes for v0.2.0

.github/workflows/main.yml, src/test/docker/el7/Dockerfile, src/test/docker/el8/Dockerfile, t/t0003-barrier.t, t/t0004-bizcard.t
Problem: builds are failing because the ompi v5.0.x branch now requires openpmix v4.2.2.
For the moment, reconfigure CI to lock in the ompi v5.0.0rc2 tag, which works with openpmix v4.1.1.
Thanks to @grondo for providing the patch to modernize the el builders also.
=> ci: update el builders and force ompi v5.0.0rc2

config/ax_flux_core.m4, src/shell/plugins/Makefile.am, src/shell/plugins/main.c, src/shell/plugins/maps.c, src/shell/plugins/maps.h
Problem: code for generating "maps" is no longer needed now that flux-core has taskmaps.
Use the new interface and throw away some code.
=> plugin: use flux taskmap class to generate lpeers, procmap

src/shell/plugins/infovec.c, src/shell/plugins/infovec.h, src/shell/plugins/main.c, src/shell/plugins/test/infovec.c
Problem: the latest ompi v5 work requires a newer openpmix, but flux-pmix fails with the newer openpmix, apparently because it doesn't populate the PMIX_PROC_INFO_ARRAY.
Take care of this, then bump the openpmix version used in CI.
=> plugin: populate PMIX_PROC_INFO_ARRAY

.github/workflows/main.yml, src/test/docker/bionic/Dockerfile, src/test/docker/el7/Dockerfile, src/test/docker/el8/Dockerfile, src/test/docker/fedora34/Dockerfile, src/test/docker/focal/Dockerfile, t/t0003-barrier.t
This pushes the version of openpmix that we build against forward to 4.2.2.
In addition, it reverts the lock-in of ompi-v5.0.0rc2 in CI.
=> switch to openpmix 4.2.2

.github/workflows/main.yml, src/shell/plugins/codec.c, src/shell/plugins/fence.c, src/shell/plugins/infovec.c, t/src/barrier.c, t/t0003-barrier.t
Zeroing `pmix_value_t` storage before use seems to both shut up valgrind and resolve issue #69.  As pointed out by @grondo, the supposed fix may just be eliminating spurious valgrind warnings.  Why the issue goes away is unknown, but maybe there's some other effect going on in the pmix server code that I'm missing.  I guess we can reopen if it recurs.
=> fix spurious test failure and add improved debug

.github/workflows/main.yml
Problem: Github is reporting that Nodejs 12 actions are deprecated.
This includes the checkout@v2 and codecov-action@v1 actions.
Update these actions to the latest versions, matching what was done in flux-core.
=> ci: update versions of checkout and codecov actions

t/src/bizcard.c, t/src/notify.c, t/t1000-ompi-basic.t, t/t2001-osu-benchmarks.t, t/t2002-mpibench.t
Problem: since PMI-1 is always active, it's not entirely clear that the testsuite covers using pmix to bootstrap ompi version < v5.
Disable PMI-1 service with `-o mpi=off` in the MPI tests.
Add some checks in the mpi tests to ensure multiple singletons are not started.
Toss in another small change to zero more `pmix_value_t` objects in test programs.
=> make testing of ompi < v5 more robust

configure.ac, t/Makefile.am, t/src/Makefile.am, t/src/mpi_version.c, t/t1000-ompi-basic.t, t/t2001-osu-benchmarks.t, t/t2002-mpibench.t
Problem: the project cannot be built without openmpi, but it doesn't really depend on it, just a few tests.
Make openmpi optional and skip those tests if it's not configured.
Fix some outdated stuff in the `configure.ac` while we're at it.
=> build: make the ompi prereq optional

Makefile.am, README.md, configure.ac, src/upmi/Makefile.am, src/upmi/pmix.c, t/Makefile.am, t/t0008-upmi.t
flux-framework/flux-core#4865 enables broker bootstrap methods to be provided by dso plugins and drops pmix client support from the broker.  This PR re-adds support by providing a dso.
This seems better since it localizes the openpmix dependency here.
=> add PMI client plugin to enable flux to be launched by a pmix server

src/common/libutil/Makefile.am, src/common/libutil/test/unsetenv_glob.c, src/common/libutil/unsetenv_glob.c, src/common/libutil/unsetenv_glob.h, src/upmi/pmix.c, t/t0008-upmi.t
Ensure that the flux pmix client plugin  (upmi) clears PMIX_* environment variables after finalize is called, so that these variables don't leak through to Flux jobs.
=> clear PMIX_ environment variables in broker

README.md, config/ax_flux_core.m4
Problem: the minimum flux-core version required by configure is wrong.
Raise the minimum version to 0.49.0.
Also drop the installation section from the README.md since it's out of date and probably not needed anyway.
=> require flux-core 0.49.0

.github/workflows/main.yml
Problem: The el7 flux-core docker image will no longer be updated because it is being dropped from the matrix of test images in CI.
Drop the el7 build in flux-pmix CI as well. Move chain_lint=t to another builder so that at least one build continues to run with --chain-lint.
=> ci: remove el7 build

.github/workflows/main.yml, src/shell/plugins/interthread.c, src/shell/plugins/main.c
Problem: recent changes in flux-core have made the `shmem://` connector less convenient to use, and broke flux-pmix.
This swaps out the back-to-back `flux_t` handles, used for sending messages from the pmix server thread to the shell thread, for a `struct flux_msglist` protected by mutexes.  This should work with all recent flux-core versions, and doesn't require the flux shell to take on a zeromq context, which brings with it some potential issues.
Also CI is updated to build ompi 5.0.0rc12 rather than the 5.0.x development branch, which was failing.  We'll deal with getting CI back to tracking upstream 5.0.x development later.
=> plugin: use a simpler strategy for the interthread channel

src/shell/plugins/codec.c, src/shell/plugins/codec.h, src/shell/plugins/notify.c, src/shell/plugins/test/codec.c
Problem: at one point while working on #89, `t0006-notify.t` began segfaulting.  The segfault disappeared in the eventual solution to #89, however there really was a bug there causing stack corruption.
Fix two problems with message encoding for pmix notifications, and improve unit tests for codec.c.
=> plugin: pmix notification encoding problems

NEWS.md
Problem: 0.4.0 has no release notes.
Add some.
=> NEWS: prep for 0.4.0 release

src/shell/plugins/main.c
Problem: flux-pmix does not yet share hwloc with MPI, which forces MPI to go looking for it, sometimes at great cost to performance.
For the time being, tell flux-core to share a hwloc xml file by setting the -o hwloc.xmlfile shell option.
Later we will want to fix #31 properly and drop this.
=> plugin: set hwloc.xmlfile shell option

src/shell/plugins/interthread.c
Problem: the raw message payload interfaces are changing to use a size_t instead of int.
Update usage in interthread.
flux-framework/flux-core#6467 must be merged before this will pass CI.
=> track raw payload accessor API changes in core

configure.ac
Problem: compilation fails in the TOSS 5 build farm with pmix-3.2.5.
pmix.c: In function 'op_initialize.part.0':
pmix.c:175:10: error: 'PMIx_Get' reading 512 bytes from a region of size 14 [-Werror=stringop-overread]
175 |     rc = PMIx_Get (&proc, PMIX_JOB_SIZE, NULL, 0, &val);
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pmix.c:175:10: note: referencing argument 2 of type 'const char *'
In file included from pmix.c:21:
/usr/include/pmix.h:203:27: note: in a call to function 'PMIx_Get'
203 | PMIX_EXPORT pmix_status_t PMIx_Get(const pmix_proc_t *proc, const pmix_key_t key,
|                           ^~~~~~~~
cc1: all warnings being treated as errors
This is probably due to the fact that PMIx_Get() in pmix-3.2.5 is prototyped with the second arg effectively 'const char …
=> build: fix compilation on el9 with older pmix releases

.github/workflows/main.yml, src/test/docker/el8/Dockerfile, src/test/docker/el9/Dockerfile, src/test/docker/fedora40/Dockerfile
Problem: ci is building fedora34, which isn't being updated anymore in flux-core.  Also ci is missing an el9 builder.
Add  an el9 builder and update fedora34 to fedora40.
=> ci:  add fedora40 and el9 builders

src/shell/plugins/interthread.c
Problem: the interthread channel will be harder to maintain than necessary due to its use of the obscure `flux_msglist` pollfd/pollevents interface, an fd watcher, and a pthread mutex.
Now that we have the interthread:// connector in flux-core, re-implement the interthread channel with back to back `flux_t` handles and a "handle watcher".
This will also allow the `flux_msglist` pollfd/pollevents interface to be retired in flux-core as this is the last user.
Also: avoid using the raw message interface so flux-pmix doesn't need to require flux-core > 0.69 for ABI compatibility.
=> simplify interthread channel implementation
